### ISSUE TITLE
Dataset stats

### ISSUE THREAD

**Issue by juhongm999** [Breaking-Bad-Dataset/Breaking-Bad-Dataset.github.io#4]
Hi authors,
I counted the number of objects in the dataset and found the statistics are different from the ones reported in the paper.
![Screenshot from 2022-09-26 05-43-18](https://user-images.githubusercontent.com/41140817/192164755-15d76b82-42fc-446f-ae8c-e5101f8d2eab.png)

![Screenshot from 2022-09-26 05-44-40](https://user-images.githubusercontent.com/41140817/192164759-6fd14e06-759e-4862-9679-c8a8bb02ffaf.png)

The reported number of objects for Everyday and Others count to 498 and 9772 respectively while I have 542 and 9375.
Do you know if I'm missing something?

Thanks.

**Comment by juhongm999** [comment]
Also I have found that there is something missing files in split file "data_split/everyday.train.txt"
According to the paper, there must be 100 fracture patterns in each directory listed in "data_split/everyday.train.txt".
However, I found some of directories are either missing or only contains 96 fracture patterns:

everyday/Vase/12d643221a3edaa4ab361b6be63163da - 0

everyday/Vase/12d643221a3edaa4ab361b6be63163da - 0

everyday/PillBottle/ec42773c595dc08e4d678187b8261d95 - 96

Will you please resolve this issue?
Thanks!

**Comment by SlotFormer** [comment]
Hi, thank you for your interest in our work. Regarding the first question, we're looking into it, but the server undergoes some issues and we've removed the original dataset, so it may take some time. Also, we might release an updated version of the dataset in the future to filter some items

Regarding the second question, yes we also observe this. This is because we're doing rejection sampling during data generation to filter out some fractures (e.g. num_pieces > 100, or duplicate fracture mode). When we parallelly run the code, we set a MAX_TIME_LIMIT for each process. So there are some processes that will exceed this time limit (due to some reasons, e.g. mesh quality too bad), thus producing less than 100 fractures. For those with 0 fracture, maybe that's because the assigned CPU node (we use Slurm) has some issues so the code doesn't run? We do plan to study these issues more comprehensively in the future

**Comment by Wuziyi616** [comment]
Hi, thank you for your interest in our work. Regarding the first question, we're looking into it, but the server undergoes some issues and we've removed the original dataset, so it may take some time. Also, we might release an updated version of the dataset in the future to filter some items

Regarding the second question, yes we also observe this. This is because we're doing rejection sampling during data generation to filter out some fractures (e.g. num_pieces > 100, or duplicate fracture mode). When we parallelly run the code, we set a MAX_TIME_LIMIT for each process. So there are some processes that will exceed this time limit (due to some reasons, e.g. mesh quality too bad), thus producing less than 100 fractures. For those with 0 fracture, maybe that's because the assigned CPU node (we use Slurm) has some issues so the code doesn't run? We do plan to study these issues more comprehensively in the future

**Comment by juhongm999** [comment]
Thanks for the answers
By the way, congratulation for the acceptance!

**Comment by Wuziyi616** [comment]
@juhongm999 hi, I double-check our data, it's true that the `everyday` subset has 542 shapes in total (also the three shapes you point out, indeed they have 0, 0, 98 fractures; the other shapes should be fine)

And for the `other` subset, you are also right. It seems that we report the wrong version of stats to the paper. We'll correct this in the camera-ready version. Thank you so much for pointing out!
