### ISSUE TITLE
Question regarding the benchmarking evaluation and excluding NSM from the comparison

### ISSUE THREAD

**Issue by ttsesm** [Breaking-Bad-Dataset/Breaking-Bad-Dataset.github.io#5]
Hi, I was going through the paper and in the baseline methods that you consider for the benchmark you claim that you are not using NSM because it is a two-part assembly method and not suitable for a multi-part assembly problem. 

My question is then why you didn't do an ablation study where `min_num_part=2` and `max_num_part=2` were set to 2? In that case, NSM could be compared with all the other baseline methods in a fair way without any issues.

Thanks.

**Comment by Wuziyi616** [comment]
First of all, thank you for your interest in our work. This is a good point, we didn't realize this solution back to the submission time actually.. One issue I can think of is that the data samples with only 2 fractures are too limited (I don't have the number now cause there are some issues on the server where we store the generated dataset). This is because, in Breaking Bad we break the shapes in a *natural* way, while only breaking into 2 pieces is quite rare in reality.

TBH the everyday subset is already quite limited in the amount of data, so picking only data with 2 pieces may not be enough to train a model. At least NSM uses much more data in their paper, which is necessary because the Transformer module is very data hungry. I wouldn't expect NSM to perform well if trained only on 2-piece data in Breaking Bad

**Comment by ttsesm** [comment]
> First of all, thank you for your interest in our work. This is a good point, we didn't realize this solution back to the submission time actually.. One issue I can think of is that the data samples with only 2 fractures are too limited (I don't have the number now cause there are some issues on the server where we store the generated dataset). This is because, in Breaking Bad we break the shapes in a _natural_ way, while only breaking into 2 pieces is quite rare in reality.
> 
> TBH the everyday subset is already quite limited in the amount of data, so picking only data with 2 pieces may not be enough to train a model. At least NSM uses much more data in their paper, which is necessary because the Transformer module is very data hungry. I wouldn't expect NSM to perform well if trained only on 2-piece data in Breaking Bad

Hi @Wuziyi616, thank you for the reply. 

Well according with my [calculations](https://github.com/Breaking-Bad-Dataset/Breaking-Bad-Dataset.github.io/issues/1#issuecomment-1173762151) the everyday subset has 13531 pair-wise fragmented cases, the artifacts subset 6228 and the other subset has 209355. Do you think that these aforementioned 2-piece subsets are not enough to train the NSM model? I am trying to do this only 2-piece training/testing experiment by myself on the everyday subset but indeed I am getting bad results and I am trying to figure out why. Thanks.

**Comment by Wuziyi616** [comment]
I think 13,531 is indeed hard, because NSM uses 201,590 (see our paper Table.1 stats for NSM dataset). Also, their cutting is generated from some simple parametric curves -- the surface feature is easier to learn, than the naturally broken surface in Breaking Bad.

Besides, some fracture in Breaking Bad is, I'll say, nearly impossible to solve. For example, some fractures are just chip-like, their volume is very small compared to other fractures (see our gallery on the website). We're planning to add volume constraint to the generation code (e.g. if there are N parts, then each part should have a volume > (total_volume / 2N) ) and produce another release of Everyday in the future. This might make the learning easier

**Comment by Wuziyi616** [comment]
BTW, do you train the model on all the everyday categories, or per-category? IIRC NSM did per-category training. So you may also want to start from categories with the most shapes in the everyday subset?

**Comment by ttsesm** [comment]
> I think 13,531 is indeed hard, because NSM uses 201,590 (see our paper Table.1 stats for NSM dataset). Also, their cutting is generated from some simple parametric curves -- the surface feature is easier to learn, than the naturally broken surface in Breaking Bad.
> 
Yes that's true. Actually now I am looking to use the other subset instead since it has a bigger amount of 2-pieces fragmentation in comparison to the everyday subset. 

> Besides, some fracture in Breaking Bad is, I'll say, nearly impossible to solve. For example, some fractures are just chip-like, their volume is very small compared to other fractures (see our gallery on the website). We're planning to add volume constraint to the generation code (e.g. if there are N parts, then each part should have a volume > (total_volume / 2N) ) and produce another release of Everyday in the future. This might make the learning easier
>
Yes, this is also true. However, one issue that I see is that when you have two pieces from an object which are imbalanced, meaning that you have a small piece and a bigger piece when you do the point subsampling to 1024 point per piece you end up with two pieces with different density. The smaller piece is more dense with the edges the structure of the piece being more accurate while the bigger piece is more sparse where the structure and the shape of the piece is harder to interpret.

> BTW, do you train the model on all the everyday categories, or per-category? IIRC NSM did per-category training. So you may also want to start from categories with the most shapes in the everyday subset?
>
No, I am training in the whole everyday subset, not per category. If I go per category then the amount of pcds is gonna be even smaller. Thus, I am not expecting this to help.

**Comment by Wuziyi616** [comment]
> Yes, this is also true. However, one issue that I see is that when you have two pieces from an object which are imbalanced, meaning that you have a small piece and a bigger piece when you do the point subsampling to 1024 point per piece you end up with two pieces with different density. The smaller piece is more dense with the edges the structure of the piece being more accurate while the bigger piece is more sparse where the structure and the shape of the piece is harder to interpret.

Yes, we also observe this, that's why we want to constrain the volume so that the sampled point density can be similar. We can also sample to the same density, but that will cause the num_points different, so that very hard to do batching. (Of course one can use advanced data structure to handle this, but we don't implement it right now)

> If I go per category then the amount of pcds is gonna be even smaller. Thus, I am not expecting this to help.

Maybe you can merge all the `Bottle` categories? E.g. Bottle, DrinkBottle, PillBottle, BeerBottle. We did try this in our preliminary experiments, and it indeed improves the performance of all bottle categories
